web-client: Compile with `-C opt-level=1` everywhere
This avoids the following error:
```
Error: failed to deserialize Wasm module

Caused by:
    0: failed to parse code section
    1: too many locals: locals exceed maximum (at offset 0x…)
```